<a href="https://colab.research.google.com/github/laxitdange28-tech/numpy-notes/blob/main/class2file.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##1. Attributes of an Array

Introduce attributes that describe the array.

Attributes: .shape, .ndim, .size, .dtype.

In [2]:
import numpy as np

arr =[[1,2,3],[4,5,6],[7,8,9]]
arr = np.array(arr)
print(arr)

# . shape
print(arr.shape)

# .ndim --> number of dimension
print(arr.ndim)

# .size ---> number of element
print(arr.size)

# .dtype ---> data type inside your array
print(arr.dtype)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
2
9
int64


##Indexing and Slicing
Now we have Indexing and slicing aswell and for that we are going to see 1d and 2d indexing lets start with **1D indexing** and it is similar to list.

In [3]:
arr = np.array([10,20,30,40,50])

# 1D array indexing and slicing = list

print(arr[3])
print(arr[-1])
print(arr[-3])


40
50
30


Now lets see the 2D indexing aswell

In [4]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

#indexing
# arr[row,column]

print(arr[0,1])
print(arr[1,2])
print(arr[2,0])

2
6
7


In [5]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr[0:2,0:2])

[[1 2]
 [4 5]]


In [6]:
print(arr[1:3,1:3])

[[5 6]
 [8 9]]


In [7]:
print(arr[1:,1:2])

[[5]
 [8]]


Now we can also do the slicing lets see the **slicing in 1D**

1D slicing was really easy now lets see the **slicing in 2D**

In [8]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr[0:2,0:2])

[[1 2]
 [4 5]]


There is one more thing known as **Boolean indexing**

In [9]:
arr = np.array([1,2,3,4,5,6])
print(arr>2)

[False False  True  True  True  True]


In [10]:
print(arr[arr>2])

[3 4 5 6]


## Reshaping the Array

you can also reshape the Array as you like but be accurate about the dimensions

In [15]:
arr = np.array([1,2,3,4,5,6])
print(arr.reshape(3,2))

[[1 2]
 [3 4]
 [5 6]]


In [11]:
arr = np.array([1,2,3,4,5,6])
print(arr.reshape(2,3))

[[1 2 3]
 [4 5 6]]


In [12]:
aaa = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(aaa.reshape(2,3,2))

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


## Flattening of an array

you can convert the 2D array to 1D using the Flattening Function

In [13]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr.flatten())

[1 2 3 4 5 6 7 8 9]


In [14]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr.ravel())

[1 2 3 4 5 6 7 8 9]
