<a href="https://colab.research.google.com/github/laxitdange28-tech/numpy-notes/blob/main/Class1file.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Using NumPy**

Once you've installed NumPy you can import it as a library:

In [ ]:
pip install numpy


Numpy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy: vectors,arrays,matrices, and number generation. Let's start by discussing arrays.

# Numpy Arrays

NumPy arrays are the main way we will use Numpy throughout the course. Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

Let's begin our introduction by exploring how to create NumPy arrays.

## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [ ]:
import numpy as np

l = [10,20,30,40,50]
array  = np.array(l)
print(array)


[10 20 30 40 50]


Lets create a matrix using list

In [ ]:
a = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
    ]

matrix = np.array(a)
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Now lets see how matlix looks like using numpy arrays

## Built-in Methods

there are lots of build in methods to create an array lets create some and see

np.zeros(), np.ones(), np.full()

np.arange(), np.linspace()

np.eye()

In [ ]:
a = np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [ ]:
#np.zeros() for matrix
#rows and columns

# np.zeros((3,4))
np.zeros([3,4]) # row , column

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
#ones array --> np.onses()
ones = np.ones(5)
ones

array([1., 1., 1., 1., 1.])

In [ ]:
#ones array matarix --> np.onses()
np.ones([3,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
# creat 1D array and fill value
np.full(3,4)# size , value

array([4, 4, 4])

In [ ]:
# Creates an array filled with a specified value.
np.full([3,3],7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [ ]:
# Array with a range of values
#np.arange
arr = np.arange(0,10,2)
arr

array([0, 2, 4, 6, 8])

In [ ]:
# Identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# Evenly spaced values
np.linspace(0,1,5)# start=0,stop = 10, value = 5

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
np.random.rand(2,3) # rows,columns

array([[0.9936593 , 0.94299952, 0.28759861],
       [0.94973009, 0.96685995, 0.57327095]])

In [ ]:
# np.random.randint(start,stop,(row,columns))
np.random.randint(0,10,(3,3))

array([[3, 0, 2],
       [5, 0, 9],
       [4, 3, 8]])

arange → step-based values

linspace → fixed number of values

eye → identity matrix

rand → random floats (0–1)

randint → random integers in a range

randn → random values from bell curve distribution