<a href="https://colab.research.google.com/github/laxitdange28-tech/numpy-notes/blob/main/class3file.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Numpy array operations

Lets first see how arrays behave like “vectors/matrices” when operations happen element-wise.

In [ ]:
import numpy as np

In [ ]:
a = np.array([1, 2, 3, 4])
b = np.array([1, 0, 1, 0])

print(a + b)
print(a - b)
print(a * b)

[2 2 4 4]
[0 2 2 4]
[1 0 3 0]


These things are already different from List and if we talk about one more special power it is **Broadcasting**

In [ ]:
arr = np.array([10,20,30,40])
print(arr*5)

[ 50 100 150 200]


Even these things work with different shaped array the calculations will happen on every row. but dimensions must match

In [ ]:
a = np.array([[10,20,30],[40,50,60]])
b = np.array([1,2,3])
print(a+b)

[[11 22 33]
 [41 52 63]]


#Aggregate Functions

These functions are used to calculate the statistics on arrays.

In [ ]:
arr = np.array([10,20,30,40,50])
#min
print(arr.min())

#max
print(arr.max())

#sum
print(arr.sum())

#min
print(arr.mean())

#stander daviation
print(arr.std())

#variance
print(arr.var())

10
50
150
30.0
14.142135623730951
200.0


You can also do the axis based operations row-Wise and Colum-wise

In [ ]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

#axis = 0 --> Columns
#axis = 1 --> Row
print(f'sum of all: {arr.sum()}')
print(f'sum of rows: {arr.sum(axis=1)}')
print(f'sum of columns: {arr.sum(axis=0)}')

sum of all: 45
sum of rows: [ 6 15 24]
sum of columns: [12 15 18]
