<a href="https://colab.research.google.com/github/laxitdange28-tech/numpy-notes/blob/main/class4file.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Fancy Indexing
you can Pick elements from specific positions using a list/array of indices.

In [2]:
import numpy as np

In [3]:
arr = np.array([10,20,30,40,50])
# pick elements at position 0,2,4

print(arr[[0,2,3]])

[10 30 40]


You can do this fancy indexing in 2D Matrix aswell

In [6]:
arr = np.array([[10,20,30],[40,50,60],[70,80,90]])
print(arr[[0,1,2],[0,1,2]])


[10 50 90]
[20 60]


In [13]:
matarix = np.arange(1,13).reshape(3,4)
print(matarix)
print(matarix[[0,1],[1,2]])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[2 7]


In [11]:
print(matarix[[1,2],[0,2]])

[ 5 11]


##Conditional Selection
Find values based on conditions or replace them.

In [17]:
arr = np.array([5,7,11,18,30])

#we will get the indices only
# which are greter than 10
print(np.where(arr>10))

# array me jaha bhi 10 se choti values
#aa rhi hai waha 0 se replace kar do
print(np.where(arr>10,arr,0))

(array([2, 3, 4]),)
[ 0  0 11 18 30]


In [20]:
arr2 = np.array([23,35,30,50,100,75,80])
print(np.where(arr2>55,arr2,0))

[  0   0   0   0 100  75  80]


##Sorting & Ordering
np.sort() → returns sorted array

np.argsort() → returns indices of sorted order

In [21]:
#Aam Zindagi
arr = np.array([2,10,56,1,54])
print(np.sort(arr))

[ 1  2 10 54 56]


In [31]:
# Matrix sort
arr = np.array([[2,10,56],[1,54,23]])
# row wise sort (axis = 1)
print(np.sort(arr,axis=1))
# column wise sort (axis = 0)
print(np.sort(arr,axis=0))
#sort complete matrix
np.sort(arr)

[[ 2 10 56]
 [ 1 23 54]]
[[ 1 10 23]
 [ 2 54 56]]


array([[ 2, 10, 56],
       [ 1, 23, 54]])

In [23]:
index = np.array([2,10,56,1,54])
print(np.argsort(index))

[3 0 1 4 2]


##Concatenation & Stacking

In [29]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(np.concatenate([a,b]))

[1 2 3 4 5 6]


Vertical & Horizontal Stacking

In [32]:
arr = np.array([[1,2,3],[4,5,6]])
# vertical staking
arr2 = np.array([[7,8,9],[10,11,12]])
print(np.vstack([arr,arr2]))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [33]:
arr = np.array([[1,2,3],[4,5,6]])
# horizontal staking
arr2 = np.array([[7,8,9],[10,11,12]])
print(np.hstack([arr,arr2]))

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [38]:
arr = np.array([[1,2,3],[4,5,6]])

for i in arr:
  for j in i:
    print(j)


1
2
3
4
5
6


In [37]:
arr = np.array([[1,2,34,5,6]])
x =arr.copy()
arr[0]=12
print(x)
y =arr.view()
arr[0] = 12
print(y)


[[ 1  2 34  5  6]]
[[12 12 12 12 12]]
