<a href="https://colab.research.google.com/github/laxitdange28-tech/numpy-notes/blob/main/Complete_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#What is NumPy?

"NumPy is a Python library used for numerical computing. It provides a powerful N-dimensional array object and functions for performing fast mathematical, statistical, and matrix operations efficiently."


#Why is NumPy Faster Than Lists?

NumPy is faster than Python lists because it stores data in contiguous memory, uses fixed data types, and performs vectorized operations through optimized C code. This reduces memory usage and significantly improves execution speed for numerical computations.

#Which Language is NumPy written in?

NumPy is a Python library and is written partially in Python, but most of the parts that require fast computation are written in C or C++.



#Create a NumPy ndarray Object
NumPy is used to work with arrays. The array object in NumPy is called ndarray.

We can create a NumPy ndarray object by using the array() function.

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


#Dimensions in Arrays


#0-D Array (Scalar)

1. Contains only one element.

2. No rows and columns.

3. Called a Scalar.


In [ ]:
arr = np.array(42)
print(arr)

42


# 1-D Arrays

A collection of values in a single row.

1. Has one axis.

2. Similar to a Python list.

3. Used for storing a sequence of values.



In [ ]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)


[1 2 3 4 5]


# 2-D Array (Matrix)

Data arranged in rows and columns.

1. Has 2 axes (rows and columns).
2. Similar to a table or Excel sheet.
3. Most commonly used dimension.

In [ ]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(arr)

[[1 2 3]
 [4 5 6]]


# 3-D Array (Tensor)

Multiple 2-D arrays stacked together.

1. Has 3 axes.
2. Think of it as multiple matrices.
3. Used in Machine Learning, Deep Learning, and Image Processing.

In [ ]:
arr = np.array([
    [[1,2,3],
     [4,5,6]],

    [[7,8,9],
     [10,11,12]]
])

print(arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


#Check Number of Dimensions?
NumPy Arrays provides the ndim attribute that returns an integer that tells us how many dimensions the array have.

In [ ]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)


0
1
2
3


In [ ]:
#When the array is created, you can define the number of dimensions by using the ndmin argument.
arr = np.array([1,2,3], ndmin = 3)
print(arr)

[[[1 2 3]]]


# NumPy Array Indexing

Indexing means accessing specific elements from an array using their position (index).

Indexing starts from 0 in NumPy.

# Indexing in 1-D Array

In [ ]:
arr = np.array([10,20,30,40])
print(arr[0])

10


# Negative Indexing

Negative indexing starts from the end.

In [ ]:
arr = np.array([10,20,30,40])
print(arr[-1])
print(arr[-3])

40
20


#2. Indexing in 2-D Array

[

 [10, 20, 30],   ← Row 0

 [40, 50, 60]    ← Row 1

]

Syntax --> arr[row_index, column_index]

In [ ]:
arr = np.array([
    [10,20,30],
    [40,50,60]
])

print(arr[0,2]) # 30
print((arr[1,1])) #50

30
50


# 3. Indexing in 3-D Array

Syntax  ---> arr[matrix, row, column]

In [ ]:
arr = np.array([
  [
    [1,2,3],
    [4,5,6]
  ],

  [
      [7,8,9],
      [10,11,12]
  ]
])


print(arr[0,0,1])#2
print(arr[1,1,2])

2
12


# Fancy Indexing

Select multiple elements at once.

arr[[i,j,k]]

In [ ]:
arr = np.array([10,20,30,40,50])

print(arr[[0,2,4]])

[10 30 50]


#Boolean Indexing

Filter data using conditions.


In [ ]:
arr = np.array([10,20,30,40,50])

print(arr[arr > 25])

[30 40 50]


#Difference Between List Indexing and NumPy Indexing

In [ ]:
# list  indexing

l = [[1,2,3],[4,5,6]]
print(l[1][1])

#  numpy indexing
arr = np.array(l)
print(arr[1,1])


5
5
[[1 2 3]
 [4 5 6]]


# NumPy Array Slicing

Slicing means extracting a portion (subset) of an array.

Instead of accessing one element (indexing), slicing accesses multiple elements.

Syntax

array[start : stop : step]

# 1D Array Slicing

In [ ]:
import numpy as np
arr = np.array([10,20,30,40,50,60,70])

# Get elements from index 1 to 4

print(arr[1:5])

# Get elements from index 3 to the end
print(arr[3:])

# Get elements from the beginning to index 4
print(arr[:5])

print(arr[-5:-1])

[20 30 40 50]
[40 50 60 70]
[10 20 30 40 50]


# 2D Array Slicing

In [ ]:
import numpy as np
arr = np.array([
    [10,20,30,40],
    [50,60,70,80],
    [90,100,110,120]
])

print(arr[0,:]) # First Row

print(arr[:,0]) #  First column

print(arr[1:,1])

print(arr[1:,1:3])

print(arr[1,1:3])

[10 20 30 40]
[10 50 90]
[ 60 100]
[[ 60  70]
 [100 110]]
[60 70]


# 3D Array Slicing


In [ ]:
import numpy as np
arr = np.array([
    [[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]]
])

# print(arr[0])

# Get First Row of First Matrix
print(arr[0,0,:])

# Get First Row of Second Matrix
print(arr[1,0])

# Get Second Row of First Matrix
print(arr[0,1])

# Get Second Row of Second Matrix
print(arr[1,1])


[1 2 3]
[7 8 9]
[4 5 6]
[10 11 12]


In [ ]:

print(arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


# Difference Between Indexing and Slicing

1. Indexing

Returns a single element


2. Slicing

Returns multiple elements.


# NumPy Data Types (dtype)

Data Type (dtype) tells NumPy what kind of data is stored in an array.

1. strings - used to represent text data, the text is given under quote marks. e. g. "ABCD"
2. integer - used to represent integer numbers. e.g. -1, -2, -3
3. float - used to represent real numbers. e.g. 1.2, 42.42
4. boolean - used to represent True or False.
5. complex - used to represent complex numbers. e.g. 1.0 + 2.0j, 1.5 + 2.5j


# Check Data Type

Use the dtype attribute.

In [ ]:
import numpy as np
arr = np.array([10,20,30,40])
print(arr.dtype)

int64


#Common NumPy Data Types
| Data Type    | Description           | Example |
| ------------ | --------------------- | ------- |
| `int8`       | Integer (-128 to 127) | 10      |
| `int16`      | Integer               | 1000    |
| `int32`      | Integer               | 50000   |
| `int64`      | Integer               | 100000  |
| `float32`    | Decimal Number        | 3.14    |
| `float64`    | Decimal Number        | 3.14159 |
| `bool`       | True/False            | True    |
| `complex128` | Complex Number        | 2+3j    |
| `str`        | String                | "Hello" |


# Float Array

In [ ]:
arr = np.array([1.5,2.5,3.5])
print(arr.dtype)

float64


# String Array

In [ ]:
arr = np.array(["Python", "NumPy"])

print(arr.dtype) #<U6 means Unicode string with maximum length 6.

<U6


# Boolean Array

In [ ]:
arr = np.array([True, False, True])

print(arr.dtype)

bool


# Specify Data Type While Creating Array

Use dtype.

In [ ]:
arr = np.array([1,2,3], dtype = "f")
print(arr)
print(arr.dtype)

[1. 2. 3.]
float32


# Convert Data Type (astype())

# Integer → Float

In [ ]:
arr = np.array([1,2,3])
new_array = arr.astype(float)
print(new_array)
print(new_array.dtype)

[1. 2. 3.]
float64


# Float → Integer

In [ ]:
arr = np.array([1.5,2.5,3.5])
new_array = arr.astype(int)
print(new_array)
print(new_array.dtype) #Decimal part is removed, not rounded.

[1 2 3]
int64


# Integer → Boolean

In [ ]:
arr = np.array([1,0,2,3,0,5])
new_array = arr.astype(bool)
print(new_array)
print(new_array.dtype)

[ True False  True  True False  True]
bool


# Why Data Types Matter?

1. Faster Computation ---> NumPy knows all elements are integers, so operations are optimized.

2. Memory Efficiency

# Q1: What is dtype in NumPy?

Answer:

dtype is an attribute that defines the type of data stored in a NumPy array. It helps NumPy perform operations efficiently and use memory optimally.

# Memory Trick
dtype  = Data Type

astype = Change Data Type

itemsize = Memory Used by One Element

# NumPy Array Copy vs View

# 1. Copy -- > A copy creates a new array with its own memory location.

Dono arrays ka data same hai, lekin memory alag-alag hai.

# Real-Life Example
# Copy

Imagine photocopying a document.

Original Document
      ↓
Photocopy

Writing on the photocopy does not change the original.

In [ ]:
import numpy as np

arr = np.array([10, 20, 30, 40])

new_arr = arr.copy()

new_arr[0] = 100

print(arr)
print(new_arr)

# Explanation
new_arr is a completely separate array.

Changing new_arr does not affect arr.


# Memory Diagram
arr     ----> [10 20 30 40]

new_arr ------> [10 20 30 40]

Different memory locations.

# 2. View

A view does not create a new copy of data.

It only creates another way to look at the same data.

In [ ]:
import numpy as np

arr = np.array([10, 20, 30, 40])

new_arr = arr.view()

new_arr[0] = 100

print(arr)
print(new_arr)

# Explanation
Both arrays share the same data.
Changing one affects the other.

# Memory Diagram
arr

        \
          ---> [10 20 30 40]
        /
new_arr


# arr aur view_arr dono same memory block ko point karte hain.

#Rule to Remember:

copy() → Safe, independent array.

view() → Fast, memory-efficient, but linked to the original array.

# Check Base Attribute

NumPy provides .base to identify whether an array owns its data.

In [ ]:
# Copy
arr = np.array([1,2,3])

copy_arr = arr.copy()

print(copy_arr.base) # None means it owns its own data.

In [ ]:
# Viwe
arr = np.array([1,2,3])

view_arr = arr.view()

print(view_arr.base) # This indicates that the view refers to the original array.

| Feature                       | Copy (`copy()`)                       | View (`view()`)                             |
| ----------------------------- | ------------------------------------- | ------------------------------------------- |
| Memory                        | New memory allocated                  | Same memory as original                     |
| Data Shared                   | ❌ No                                  | ✅ Yes                                       |
| Changes Affect Original Array | ❌ No                                  | ✅ Yes                                       |
| Changes Affect New Array      | ❌ No                                  | ✅ Yes                                       |
| Speed                         | Slower (creates new data)             | Faster (no new data created)                |
| Memory Efficient              | ❌ Less efficient                      | ✅ More efficient                            |
| Independence                  | Completely independent                | Dependent on original                       |
| Method Used                   | `arr.copy()`                          | `arr.view()`                                |
| `base` Attribute              | `None`                                | Points to original array                    |
| Use Case                      | When you need a separate copy of data | When you want to save memory and share data |


# What is the difference between Copy and View in NumPy?

Answer:

A Copy creates a new array with its own memory, so changes do not affect the original array. A View shares the same memory as the original array, so modifications in one array are reflected in the other.

# What is Shape?

Shape tells us the structure of an array.

It shows:

Number of rows

Number of columns

Number of matrices (for 3D arrays)

Use the .shape attribute to find the shape of an array.

In [ ]:
import numpy as np

# 1D array
arr1 = np.array([1, 2, 3, 4])
print(arr1.shape)

# 2D array
arr2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr2.shape)

# 3D
arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr3.shape) # 2 matrices , 2 rows , 3 columns

(4,)
(2, 4)
(2, 2, 3)


# Dimension --> Number of dimensions

use for check dimension ----> .ndim

In [ ]:
arr = np.array([1, 2, 3, 4])
print(arr.ndim)

arr1 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr1.ndim)

1
2


# Size ---- > Total Elements

In [ ]:
# 1D array
arr = np.array([1,2,3,4])
print(arr.size)

# 2D array
arr2 = np.array([[1,2,3,4],[5,6,7,8]])
print(arr2.size)



4
8


shape = Structure

ndim  = Dimensions

size  = Total Elements

# What is Reshaping?

Reshaping means changing the shape (structure) of an array without changing its data.

For example:

1D Array  →  2D Array

2D Array  →  3D Array

3D Array  →  2D Array

NumPy provides the reshape() method for this.

# Syntax
array.reshape(new_shape)

# 1D → 2D

In [ ]:
import numpy as np

arr = np.array([1,2,3,4,5,6])

new_arr = arr.reshape(2,3)

print(new_arr)

[[1 2 3]
 [4 5 6]]


# 1D → 3D

In [ ]:
import numpy as np

arr = np.array([1,2,3,4,5,6,7,8])
new_arr = arr.reshape(2,2,2) #Meaning:- 2 matrices , 2 rows , 2 columns
print(new_arr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


# flatten() ---> use for convert 2D array in 1D

In [ ]:
# Method 1
arr = np.array([[1,2,3],[4,5,6]])
new_arr = arr.flatten()
print(new_arr)

# Method 2
arr2 = np.array([[1,2,3],[4,5,6]])
new_arr2 = arr2.reshape(-1)
print(new_arr2)

[1 2 3 4 5 6]
[1 2 3 4 5 6]


# Q1. What is reshaping in NumPy?

Answer:

Reshaping is the process of changing the shape of an array without changing its data using the reshape() method.

# Q2. What is the rule for reshaping?

Answer:

The total number of elements before and after reshaping must remain the same.

# Q3. What does -1 mean in reshape?

Answer:

-1 tells NumPy to automatically calculate that dimension based on the total number of elements.

# NumPy Array Iterating
What is Iteration?

Iteration means accessing array elements one by one using a loop.

In NumPy, we generally use a for loop to iterate through arrays.

In [ ]:
import numpy as np

arr = np.array([10, 20, 30, 40])

for x in arr:
    print(x)

10
20
30
40


In [ ]:
import numpy as np

arr = np.array([[10, 20, 30], [40, 50, 60]])

for x in arr:
    for y in x:
        print(y)

10
20
30
40
50
60


In [ ]:
import numpy as np

arr = np.array([[[10, 20], [30, 40]], [[50, 60], [70, 80]]])

for x in arr:
    for y in x:
        for z in y:
          print(z)


10
20
30
40
50
60
70
80


# NumPy nditer()

When working with multi-dimensional arrays, NumPy provides nditer().

It visits every element regardless of dimensions.

In [ ]:
import numpy as np

arr = np.array([[1,2,3],[3,4,5]])

for i in np.nditer(arr):
    print(i)

1
2
3
3
4
5


In [ ]:
import numpy as np

arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)


1
2
3
4
5
6
7
8


# Iterating with Index Using ndenumerate()

If you need both index and value:

In [ ]:
import numpy as np

arr = np.array([10, 20, 30, 40])

for i, x in np.ndenumerate(arr):
  print(i, x)

(0,) 10
(1,) 20
(2,) 30
(3,) 40


In [ ]:
import numpy as np

arr = np.array([[10, 20, 30, 40], [50, 60, 70, 80]])

for i, x in np.ndenumerate(arr):
  print(i, x)

(0, 0) 10
(0, 1) 20
(0, 2) 30
(0, 3) 40
(1, 0) 50
(1, 1) 60
(1, 2) 70
(1, 3) 80


# Q1. What is array iteration?

Answer:

Iteration is the process of accessing array elements one by one using loops.

# Q2. What is nditer()?

Answer:

nditer() is a NumPy iterator that efficiently traverses all elements of a multi-dimensional array.

# Q3. What is ndenumerate()?

Answer:

ndenumerate() returns both the index and value of each element during iteration.

# Memory Trick
for loop      → Basic Iteration 🔄

nditer()      → Every Element 🚶

ndenumerate() → Index + Value 📍

# What is Joining?

Joining means combining two or more arrays into a single array.

NumPy provides several methods for joining arrays:

concatenate()

stack()

hstack()

vstack()

dstack()

# 1. concatenate()

The most common method for joining arrays.

In [ ]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


 # 2. Joining 2D Arrays (axis=0)

In [ ]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=0) # 0 --> row

print(arr) # Row are added.


[[1 2]
 [3 4]
 [5 6]
 [7 8]]


# 3. Joining 2D Arrays (axis=1)

In [ ]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1) # 1 ---> column

print(arr) # Columns are added.


[[1 2 5 6]
 [3 4 7 8]]


# 4. stack()

stack() joins arrays along a new axis.

In [ ]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

result = np.stack((arr1, arr2))

print(result) # A new dimension is created.

[[1 2 3]
 [4 5 6]]


# 5. hstack() (Horizontal Stack)

Joins arrays horizontally.

In [ ]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

result = np.hstack((arr1, arr2))

print(result)

[1 2 3 4 5 6]


# 6. vstack() (Vertical Stack)

Joins arrays vertically.

In [ ]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

result = np.vstack((arr1, arr2))

print(result)

[[1 2 3]
 [4 5 6]]


# 7. dstack() (Depth Stack)

Joins arrays along the third dimension.

In [ ]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

result = np.dstack((arr1, arr2))

print(result)

[[[1 4]
  [2 5]
  [3 6]]]


| concatenate()                    | stack()                   |
| -------------------------------- | ------------------------- |
| Uses existing axis               | Creates new axis          |
| Shape may remain same dimensions | Shape gains one dimension |


In [ ]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

result1 = np.concatenate((arr1, arr2))

result2 = np.stack((arr1, arr2))
print(result1)
print(result2)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


# Comparison Table

| Method          | Description              |
| --------------- | ------------------------ |
| `concatenate()` | Join along existing axis |
| `stack()`       | Join along new axis      |
| `hstack()`      | Horizontal joining       |
| `vstack()`      | Vertical joining         |
| `dstack()`      | Depth-wise joining       |


# What is Splitting?

Splitting means dividing one array into multiple smaller arrays.

It is the opposite of Joining Arrays.

NumPy provides:

array_split()

split()

hsplit()

vsplit()

dsplit()

# 1. array_split()

Most commonly used splitting method.


array_split() can handle unequal divisions.

# Syntax
np.array_split(array, number_of_parts)

In [1]:
# Split into 3 Parts

import numpy as np

arr = np.array([1,2,3,4,5,6])

result = np.array_split(arr, 3)

print(result)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [2]:
arr = np.array([1,2,3,4,5])

new_arr = np.array_split(arr,3)

print(new_arr) # array_split() can handle unequal divisions.

[array([1, 2]), array([3, 4]), array([5])]


# 2. split()

Works only when equal splitting is possible.

In [5]:
arr = np.array([1,2,3,4,5,6])

new_arr = np.split(arr, 3)

print(new_arr)

[array([1, 2]), array([3, 4]), array([5, 6])]


# Difference Between split() and array_split()

| Feature               | split() | array_split() |
| --------------------- | ------- | ------------- |
| Equal split required  | ✅ Yes   | ❌ No          |
| Unequal split allowed | ❌ No    | ✅ Yes         |
| More flexible         | ❌       | ✅             |


#3. Split at Specific Indexes

Instead of number of parts, specify positions.

In [10]:
arr = np.array([1,2,3,4,5,6])

result = np.array_split(arr, [2,4]) #[index1, index2]

print(result)

[array([1, 2]), array([ 3, 14]), array([5, 6])]


# Splitting 2D Arrays

In [13]:
arr = np.array([[1,2],[3,4],[5,6],[7,8]])
new_arr = np.array_split(arr, 2)
print(new_arr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]


# 4. hsplit() (Horizontal Split)

Splits columns.

In [14]:
arr = np.array([
    [1,2,3,4],
    [5,6,7,8]
])

result = np.hsplit(arr, 2)

print(result)

[array([[1, 2],
       [5, 6]]), array([[3, 4],
       [7, 8]])]


# 5. vsplit() (Vertical Split)

Splits rows.

In [16]:
arr = np.array([[1,2],[3,4],[5,6],[7,8]])
neww_arr = np.vsplit(arr, 2)
print(neww_arr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]


# Comparison Table

| Method          | Splits Along     |
| --------------- | ---------------- |
| `array_split()` | Any axis         |
| `split()`       | Equal parts only |
| `hsplit()`      | Columns          |
| `vsplit()`      | Rows             |
| `dsplit()`      | Depth            |


# Q1. What is array splitting in NumPy?

Answer:

Splitting is the process of dividing an array into multiple sub-arrays using functions like split() and array_split().

# What is Searching?

Searching means finding:

A specific value

The position (index) of a value

Elements matching a condition

NumPy mainly uses the where() function for searching.

In [17]:
arr = np.array([10,20,30,40,50,60])

result = np.where(arr == 40)

print(result)


(array([3]),)


# serching in multiple occurences

In [19]:
arr = np.array([10,20,30,40,50,60,20])

result = np.where(arr == 20)

print(result) # 20 is found at indexes 1 and 6.

(array([1, 6]),)


# search eeven number

In [22]:
arr = np.array([11,20,35,40,55,67,70])

result = np.where(arr % 2 == 0)

print(result)

(array([1, 3, 6]),)


# Search in 2D Array

In [24]:
arr = np.array([
    [10,20],
    [30,20]
])

result = np.where(arr == 20)

print(result)

(array([0, 1]), array([1, 1]))


# Boolean Searching

Instead of indexes, get actual values.

In [23]:
arr = np.array([10,20,30,40,50])

print(arr[arr > 25])

[30 40 50]


# searchsorted()

Used to find where a value should be inserted to keep the array sorted.

In [25]:
arr = np.array([10,20,30,40])

result = np.searchsorted(arr, 25)

print(result)

2


# Comparison Table

| Function            | Purpose                         |
| ------------------- | ------------------------------- |
| `np.where()`        | Find indexes matching condition |
| `np.searchsorted()` | Find insertion position         |
| Boolean Indexing    | Return matching values          |


# Q1. What is np.where()?

Answer:

np.where() returns the indexes of elements that satisfy a specified condition

# Q2. What is searchsorted()?

Answer:

searchsorted() returns the index where a value should be inserted in a sorted array to maintain order.

# Q3. Difference Between where() and Boolean Indexing

| `where()`          | Boolean Indexing   |
| ------------------ | ------------------ |
| Returns indexes    | Returns values     |
| Used for positions | Used for filtering |

# Example

np.where(arr > 20)
# Indexes

arr[arr > 20]
# Values

# What is Sorting?

Sorting means arranging elements in a specific order.

Usually:

Ascending Order → Smallest to Largest
Descending Order → Largest to Smallest

NumPy provides the sort() function for sorting arrays.

# Important Point

np.sort() returns a new sorted array.

Original array remains unchanged.

In [27]:
import numpy as np

arr = np.array([40, 10, 30, 20])

new_arr = np.sort(arr)

print(new_arr)

[10 20 30 40]


#  Sorting a 2D Array

Description

Each row is sorted independently.

In [28]:
arr = np.array([
    [3,2,1],
    [6,5,4]
])

print(np.sort(arr))

[[1 2 3]
 [4 5 6]]


# Sorting by Axis
axis=1 (Row-wise)

In [29]:
arr = np.array([
    [3,1,2],
    [6,4,5]
])

print(np.sort(arr, axis=1))

[[1 2 3]
 [4 5 6]]


# Descending Order

NumPy directly sorts in ascending order.

Use slicing to reverse.

In [30]:
arr = np.array([40,10,30,20])

result = np.sort(arr)[::-1]

print(result)

[40 30 20 10]


# argsort()

Returns indexes of sorted elements.

In [31]:
arr = np.array([40,10,30,20])

print(np.argsort(arr))

[1 3 2 0]


| Function          | Purpose            |
| ----------------- | ------------------ |
| `np.sort()`       | Sort values        |
| `np.sort()[::-1]` | Descending sort    |
| `np.argsort()`    | Get sorted indexes |


# Q1. What is np.sort()?

Answer:

np.sort() returns a sorted copy of an array in ascending order

# Q2. Does np.sort() modify the original array?

Answer:

No. It returns a new sorted array and leaves the original array unchanged.

# Q3. What is argsort()?

Answer:

argsort() returns the indexes that would sort the array.

# A random array contains randomly generated values.

NumPy provides the random module to generate:

Random integers

Random floats

Random arrays with different shapes

# Import Random Modle

# Syntax
np.random.randint(low, high)

In [34]:
import numpy as np

num = np.random.randint(1, 10)

print(num)

2


# 2. Generate Multiple Random Integers

In [35]:
arr = np.random.randint(1, 100, size=(2,3))

print(arr)

[[44 89 14]
 [94 65 40]]


# Generate Random Float Numbers

rand()

In [37]:
arr = np.random.rand(5,2)

print(arr)

[[0.39772314 0.88733725]
 [0.07457185 0.18740389]
 [0.66390739 0.51310221]
 [0.87982791 0.39793426]
 [0.66151084 0.44989417]]


# Generate Random Float Using uniform()

# Syntax
np.random.uniform(low, high, size)

In [38]:
arr = np.random.uniform(1, 10, size=(2,3))

print(arr)

[[7.14914215 9.75259065 9.96858987]
 [9.65296113 5.16156359 3.44254489]]


# Generate Random Choice

Select random values from a list.

In [39]:
arr = np.random.choice([10,20,30,40], size=5)

print(arr)

[40 30 30 20 30]


# Generate Random 3D Array



In [40]:
arr = np.random.randint(1,10,size=(2,2,3))

print(arr)

[[[5 7 3]
  [8 6 5]]

 [[3 8 4]
  [5 3 5]]]


| Function    | Purpose                |
| ----------- | ---------------------- |
| `randint()` | Random integers        |
| `rand()`    | Random floats (0–1)    |
| `uniform()` | Random floats in range |
| `choice()`  | Random selection       |
| `seed()`    | Fix randomness         |


# Q1. What is randint()?

Answer:

randint() generates random integers within a specified range.

# Q2. What is the difference between rand() and randint()?
rand()	randint()
Returns float	Returns integer
Range 0–1	Custom range