<a href="https://colab.research.google.com/github/laxitdange28-tech/numpy-notes/blob/main/numpy_final_assign_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# Final NumPy Assignment
# Inputs khud se create karna hai



# Q1. Array Creation and Attributes

## Problem Statement
Create array [10,20,30,40,50] and print shape, ndim, size and dtype.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [1]:
import numpy as np

In [7]:
# Write your code here
arr = np.array([10,20,30,40,50])

# print shape of array
print(arr.shape)

#print Dimention of array
print(arr.ndim)

# print total size of eleement
print(arr.size)


# print datatype of array
print(arr.dtype)


(5,)
1
5
int64



# Q2. Matrix Creation

## Problem Statement
Create a 3x3 NumPy matrix and print it.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [8]:
# Write your code here
arr = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]



# Q3. Indexing Practice

## Problem Statement
Print first, third and last element from an array.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [9]:
# Write your code here
arr = np.array([10,20,30,40,50,60])
print(arr[[0,2,-1]])

[10 30 60]



# Q4. Slicing Practice

## Problem Statement
Print elements from index 2 to 5.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [10]:
# Write your code here
arr = np.array([10,20,30,40,50,60])
print(arr[2:5])

[30 40 50]



# Q5. Fancy Indexing

## Problem Statement
Print selected elements using fancy indexing.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [ ]:
# Write your code here
arr = np.array([10,20,30,40,50,60])
print(arr[[0,2,-1]])


# Q6. Conditional Selection

## Problem Statement
Print values greater than 15.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [11]:
# Write your code here
arr = np.array([10,20,30,40,50,60])
print(arr[arr>15])

[20 30 40 50 60]



# Q7. Broadcasting

## Problem Statement
Add 10 to every element of an array.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [14]:
# Write your code here
arr = np.array([1,2,3,4,5,6])
print(arr+10)

[11 12 13 14 15 16]



# Q8. Aggregate Functions

## Problem Statement
Print sum, mean, max and min.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [17]:
# Write your code here
arr = np.array([10,20,30,40,50,60])

# sum of array
print(arr.sum())

# print mean of array
print(arr.mean())

# print max of array
print(arr.max())

# print min of array
print(arr.min())

210
35.0
60
10



# Q9. Sorting

## Problem Statement
Sort an unsorted NumPy array.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [18]:
# Write your code here
arr = np.array([10,20,30,40,50,60])
print(np.sort(arr))

[10 20 30 40 50 60]



# Q10. Concatenation and Stacking

## Problem Statement
Perform concatenate and vstack on two arrays.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [21]:
# Write your code here

import numpy as np

# Create arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Concatenate arrays
concat_arr = np.concatenate((arr1, arr2))

# Vertical Stack
vstack_arr = np.vstack((arr1, arr2))

print("Concatenated Array:")
print(concat_arr)

print("\nVertically Stacked Array:")
print(vstack_arr)


Concatenated Array:
[1 2 3 4 5 6]

Vertically Stacked Array:
[[1 2 3]
 [4 5 6]]
