<a href="https://colab.research.google.com/github/laxitdange28-tech/numpy-notes/blob/main/Vectorization_Broadcasting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Vectorization Kya Hai?

Vectorization ka matlab hai arrays par operations ko without loops perform karna.

NumPy internally C language me optimized hota hai, isliye vectorized operations Python loops se bahut fast hote hain.

# Without Vectorization (Using Loop)

In [1]:
arr = [1,2,3,4,5]
result = []

for i in arr:
  result.append(i*2)

print(result)

[2, 4, 6, 8, 10]


# With Vectorization (Using NumPy)

In [2]:
import numpy as np

arr = np.array([1,2,3,4,5])
result = arr*2

print(result) # NumPy ne har element par automatically multiplication kar diya:

[ 2  4  6  8 10]


# Vectorization ke Benefits

| Benefit          | Description               |
| ---------------- | ------------------------- |
| Faster           | Loops se bahut fast       |
| Less Code        | Kam code likhna padta hai |
| Easy Readability | Code clean dikhta hai     |
| Optimized        | C backend use karta hai   |


# Broadcasting Kya Hai?

Broadcasting ek technique hai jisme NumPy different shapes ke arrays par arithmetic operations perform kar sakta hai.

Agar dimensions compatible ho to NumPy automatically smaller array ko expand kar deta hai.

# Scalar Broadcasting

In [3]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr+10)

[11 12 13 14 15]


# Row Bordcasting

In [5]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print(arr  +  np.array([10,20,30]))

[[11 22 33]
 [14 25 36]]


# Vectorization VS Broadcating

| Feature | Vectorization           | Broadcasting                  |
| ------- | ----------------------- | ----------------------------- |
| Purpose | Loops remove karna      | Different shapes handle karna |
| Speed   | Fast                    | Fast                          |
| Example | arr * 2                 | arr + scalar                  |
| Use     | Element-wise operations | Shape expansion               |


# Interview Definition

# Vectorization

Vectorization NumPy ki technique hai jisme arrays par operations bina explicit loops ke perform kiye jate hain, jisse code fast aur efficient ho jata hai.

# Broadcasting

Broadcasting NumPy ki mechanism hai jo different shapes wale arrays ko arithmetic operations ke liye compatible banati hai by virtually expanding the smaller array.